//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroBoard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rule
    {
        public int Id { get; set; }
        public string RuleExpression { get; set; }
        public string QueryString { get; set; }
        public string Success { get; set; }
        public string Alternate { get; set; }
        public string TelemetryInfo { get; set; }
    }
}
