//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroBoard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public int Id { get; set; }
        public string name { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string deviceAndSensorName { get; set; }
    
        public virtual DeviceAndSensor DeviceAndSensor { get; set; }
    }
}
