//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgroBoard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TelemetryData
    {
        public int Id { get; set; }
        public string Value { get; set; }
        public Nullable<int> TelemetryId { get; set; }
    
        public virtual Telemetry Telemetry { get; set; }
    }
}
